%%% Live end-to-end proof for piece A (PLAN_MCL_OM_MESH_WRAPPERS.md):
%%% boots mcl_om as a real OTP application (application:
%%% ensure_all_started/1, not just mcl_om_identity standalone)
%%% against a real PQ-fleet station, and confirms the migrated
%%% connection lifecycle (mcl_om_sup's own mesh pool child, via
%%% mcl_om_identity:start_mesh_pool/0) produces a pool genuinely
%%% usable for real mesh work, not just a live pid -- a real piece C
%%% publish succeeds through it.
%%%
%%% test/mcl_om_mesh_pool_SUITE.erl already proves the process-
%%% lifecycle claims (no pool child with no seeds, no boot race, OTP
%%% restarts a crashed pool) against an unreachable seed, which is the
%%% right tool for those -- this file's only job is the one thing that
%%% needs a real station: does the resulting pool actually work.
%%%
%%% The 11.x port: the seed carries the station's node id (D5 -- an
%%% unpinned dial can never connect), and the pool's identity is a
%%% puzzle-hardened pq_hybrid node key (generated by the SDK at connect
%%% when no identity_key_path is configured, at the fleet's difficulty).
%%%
%%% Lives in test_live/, NOT test/ -- excluded from the default
%%% `rebar3 eunit' and CI's main gate on purpose; see
%%% mcl_om_capabilities_live_station_tests' moduledoc for why. Run
%%% explicitly:
%%%   rebar3 as live_test eunit --dir test_live
-module(mcl_om_mesh_pool_live_station_tests).
-include_lib("eunit/include/eunit.hrl").

-define(SEED_HOST, <<"pq.station-fi-helsinki.macula.io">>).
-define(SEED_PORT, 4433).
-define(SEED_NODE_ID,
        <<16#004d1f470097ccf8826ce291900e882fdb1f20375e53901facaec0f23eb4efd8:256>>).
-define(TOPIC, <<"mcl_om_mesh_pool_live_test.topic1">>).

migrated_pool_boots_clean_and_publishes_for_real_test_() ->
    {timeout, 60, fun run/0}.

run() ->
    %% Defensive: a previous failed run in this shared VM may have left
    %% mcl_om up, and the "no boot race" claim below needs a genuinely
    %% fresh boot.
    stopped_already(mcl_om),
    Realm = crypto:strong_rand_bytes(32),
    application:load(mcl_om),
    application:set_env(mcl_om, health_port, 0),
    application:set_env(mcl_om, station_seeds,
                        [#{host => ?SEED_HOST, port => ?SEED_PORT,
                           expected_node_id => ?SEED_NODE_ID}]),
    application:set_env(mcl_om, realm, Realm),

    {ok, _} = application:ensure_all_started(mcl_om),

    %% No poll/retry here on purpose -- proving the same "no boot race"
    %% claim test/mcl_om_mesh_pool_SUITE.erl proves against an
    %% unreachable seed, this time with a real station on the other
    %% end: application:ensure_all_started/1 returning means the pool
    %% child (and so the whole supervisor tree) already started.
    {ok, Pool} = mcl_om:macula_client(),
    ?assert(is_pid(Pool)),
    ok = wait_healthy(Pool, 200),

    ?assertEqual({ok, Pool, Realm}, mcl_om:mesh_handles()),

    %% The actual point: this pool is not just alive, it is usable --
    %% a real piece C publish through it, against a real station.
    ?assertEqual(ok, mcl_om_pubsub:publish(?TOPIC, #{probe => 1},
                                           #{mode => sync})),

    application:stop(mcl_om),
    application:unload(mcl_om),
    ok.

wait_healthy(_Pool, 0) ->
    erlang:error(seed_never_healthy);
wait_healthy(Pool, N) ->
    healthy_or_wait(macula_client:status(Pool), Pool, N).

healthy_or_wait({ok, #{healthy_links := H}}, _Pool, _N) when H > 0 ->
    ok;
healthy_or_wait(_Status, Pool, N) ->
    timer:sleep(100),
    wait_healthy(Pool, N - 1).

stopped_already(App) ->
    _ = (catch application:stop(App)),
    _ = application:unload(App),
    ok.
